name: pipeline-pydata
channels:
  - defaults
dependencies:
  - appnope=0.1.0=py36hf537a9a_0
  - attrs=19.1.0=py36_1
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - ca-certificates=2019.8.28=0
  - certifi=2019.9.11=py36_0
  - cycler=0.10.0=py36hfc81398_0
  - dbus=1.13.6=h90a0687_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=h0a44026_0
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.56.2=hd9629dc_0
  - icu=58.2=h4b95b61_1
  - intel-openmp=2019.4=233
  - ipykernel=5.1.2=py36h39e3cac_0
  - ipython=7.8.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.1=py36_0
  - jinja2=2.10.1=py36_0
  - joblib=0.13.2=py36_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.0.2=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.3.3=py36_1
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.5.0=py_0
  - kiwisolver=1.1.0=py36h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - llvm-openmp=4.0.1=hcfea43d_1
  - markupsafe=1.1.1=py36h1de35cc_0
  - matplotlib=3.1.1=py36h54f8f79_0
  - mistune=0.8.4=py36h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py36hfbe908c_0
  - mkl_fft=1.0.14=py36h5e564d8_0
  - mkl_random=1.1.0=py36ha771720_0
  - nbconvert=5.6.0=py36_1
  - nbformat=4.4.0=py36h827af21_0
  - ncurses=6.1=h0a44026_1
  - notebook=6.0.1=py36_0
  - numpy=1.17.2=py36h99e6662_0
  - numpy-base=1.17.2=py36h6575580_0
  - openssl=1.1.1d=h1de35cc_2
  - pandas=0.25.1=py36h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.5.1=py_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=19.2.3=py36_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py36_0
  - ptyprocess=0.6.0=py36_0
  - pygments=2.4.2=py_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py36h655552a_2
  - pyrsistent=0.15.4=py36h1de35cc_0
  - python=3.6.9=h359304d_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2019.2=py_0
  - pyzmq=18.1.0=py36h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.5.5=py_0
  - readline=7.0=h1de35cc_5
  - scikit-learn=0.21.3=py36h27c97d8_0
  - scipy=1.3.1=py36h1410ff5_0
  - send2trash=1.5.0=py36_0
  - setuptools=41.2.0=py36_0
  - sip=4.19.8=py36h0a44026_0
  - six=1.12.0=py36_0
  - sqlite=3.29.0=ha441bb4_0
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py36_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.6=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/phigod/anaconda3/envs/pipeline-pydata

